apiVersion: v1
kind: Service
metadata:
  name: openshift
  namespace: openshift-origin
  labels:
    app: openshift-origin
    name: openshift
spec:
  type: NodePort
  ports:
    - name: openshift
      port: 8443
      targetPort: 8443
  selector:
    name: openshift
    app: openshift-origin
