apiVersion: v1
kind: Service
metadata:
  name: openshift-origin
  namespace: openshift
  labels:
    app: openshift-origin
    name: openshift-origin-service
spec:
  selector:
    app: openshift-origin
  ports:
    - name: openshift
      port: 8443
      targetPort: 8443
  type: NodePort
